use magnus::{Error, Ruby, Value, typed_data, value::{Id, ReprValue}};
use style::{properties::PropertyDeclaration, values::{computed::{AlignmentBaseline, ItemPlacement}, specified::align::AlignFlags}};

#[magnus::wrap(class = "Yass::Declarations::AlignItems")]
pub struct YAlignItems {
    item_placement: ItemPlacement
}

impl YAlignItems {
    pub fn new(item_placement: ItemPlacement) -> Self {
        Self { item_placement }
    }

    pub fn value(ruby: &Ruby, rb_self: typed_data::Obj<Self>) -> Result<Id, Error> {
        match rb_self.item_placement.value() {
            AlignFlags::AUTO => Ok(ruby.intern("auto")),
            AlignFlags::NORMAL => Ok(ruby.intern("normal")),
            AlignFlags::START => Ok(ruby.intern("start")),
            AlignFlags::END => Ok(ruby.intern("end")),
            AlignFlags::FLEX_START => Ok(ruby.intern("flex_start")),
            AlignFlags::FLEX_END => Ok(ruby.intern("flex_end")),
            AlignFlags::CENTER => Ok(ruby.intern("center")),
            AlignFlags::LEFT => Ok(ruby.intern("left")),
            AlignFlags::RIGHT => Ok(ruby.intern("right")),
            AlignFlags::BASELINE => Ok(ruby.intern("baseline")),
            AlignFlags::LAST_BASELINE => Ok(ruby.intern("last_baseline")),
            AlignFlags::STRETCH => Ok(ruby.intern("stretch")),
            AlignFlags::SELF_START => Ok(ruby.intern("self_start")),
            AlignFlags::SELF_END => Ok(ruby.intern("self_end")),
            AlignFlags::SPACE_BETWEEN => Ok(ruby.intern("space_between")),
            AlignFlags::SPACE_AROUND => Ok(ruby.intern("space_around")),
            AlignFlags::SPACE_EVENLY => Ok(ruby.intern("space_evenly")),
            AlignFlags::ANCHOR_CENTER => Ok(ruby.intern("anchor_center")),
            _ => Err(Error::new(ruby.exception_arg_error(), "unreachable"))
        }
    }
}

#[magnus::wrap(class = "Yass::Declarations::AlignmentBaseline")]
pub struct YAlignmentBaseline {
    alignment_baseline: AlignmentBaseline
}

impl YAlignmentBaseline {
    pub fn new(alignment_baseline: AlignmentBaseline) -> Self {
        Self { alignment_baseline }
    }

    pub fn value(ruby: &Ruby, rb_self: typed_data::Obj<Self>) -> Id {
        match rb_self.alignment_baseline {
            AlignmentBaseline::Baseline => ruby.intern("baseline"),
            AlignmentBaseline::TextBottom => ruby.intern("text_bottom"),
            AlignmentBaseline::Middle => ruby.intern("middle"),
            AlignmentBaseline::TextTop => ruby.intern("text_top"),
        }
    }
}

#[magnus::wrap(class = "Yass::Declaration")]
pub struct YDeclaration {
}

impl YDeclaration {
  pub fn from(declaration: &PropertyDeclaration, ruby: &Ruby) -> Result<Value, Error> {
    match declaration {
        PropertyDeclaration::AlignItems(item_placement) => {
            Ok(ruby.obj_wrap(YAlignItems::new(item_placement.clone())).as_value())
        },

        PropertyDeclaration::AlignmentBaseline(alignment_baseline) => {
            Ok(ruby.obj_wrap(YAlignmentBaseline::new(alignment_baseline.clone())).as_value())
        },

        PropertyDeclaration::AspectRatio(generic_aspect_ratio) => todo!(),
        PropertyDeclaration::BackfaceVisibility(t) => todo!(),
        PropertyDeclaration::BaselineSource(baseline_source) => todo!(),
        PropertyDeclaration::BorderCollapse(t) => todo!(),
        PropertyDeclaration::BorderImageRepeat(border_image_repeat) => todo!(),
        PropertyDeclaration::BoxSizing(t) => todo!(),
        PropertyDeclaration::CaptionSide(caption_side) => todo!(),
        PropertyDeclaration::Clear(clear) => todo!(),
        PropertyDeclaration::ColumnCount(generic_column_count) => todo!(),
        PropertyDeclaration::ColumnSpan(t) => todo!(),
        PropertyDeclaration::Contain(contain) => todo!(),
        PropertyDeclaration::ContainerType(container_type) => todo!(),
        PropertyDeclaration::Direction(t) => todo!(),
        PropertyDeclaration::Display(display) => todo!(),
        PropertyDeclaration::EmptyCells(t) => todo!(),
        PropertyDeclaration::FlexDirection(t) => todo!(),
        PropertyDeclaration::FlexWrap(t) => todo!(),
        PropertyDeclaration::Float(float) => todo!(),
        PropertyDeclaration::FontLanguageOverride(font_language_override) => todo!(),
        PropertyDeclaration::FontOpticalSizing(t) => todo!(),
        PropertyDeclaration::FontStretch(font_stretch) => todo!(),
        PropertyDeclaration::FontStyle(font_style) => todo!(),
        PropertyDeclaration::FontSynthesisWeight(font_synthesis) => todo!(),
        PropertyDeclaration::FontVariantCaps(t) => todo!(),
        PropertyDeclaration::FontWeight(font_weight) => todo!(),
        PropertyDeclaration::GridAutoFlow(grid_auto_flow) => todo!(),
        PropertyDeclaration::ImageRendering(image_rendering) => todo!(),
        PropertyDeclaration::Isolation(t) => todo!(),
        PropertyDeclaration::JustifyItems(justify_items) => todo!(),
        PropertyDeclaration::LineBreak(line_break) => todo!(),
        PropertyDeclaration::ListStylePosition(t) => todo!(),
        PropertyDeclaration::MixBlendMode(t) => todo!(),
        PropertyDeclaration::ObjectFit(t) => todo!(),
        PropertyDeclaration::Opacity(opacity) => todo!(),
        PropertyDeclaration::Order(integer) => todo!(),
        PropertyDeclaration::OutlineStyle(outline_style) => todo!(),
        PropertyDeclaration::OverflowWrap(overflow_wrap) => todo!(),
        PropertyDeclaration::PointerEvents(pointer_events) => todo!(),
        PropertyDeclaration::Position(position_property) => todo!(),
        PropertyDeclaration::PositionArea(position_area) => todo!(),
        PropertyDeclaration::ServoOverflowClipBox(t) => todo!(),
        PropertyDeclaration::ServoTopLayer(t) => todo!(),
        PropertyDeclaration::TableLayout(t) => todo!(),
        PropertyDeclaration::TextAlign(text_align) => todo!(),
        PropertyDeclaration::TextAlignLast(text_align_last) => todo!(),
        PropertyDeclaration::TextDecorationLine(text_decoration_line) => todo!(),
        PropertyDeclaration::TextDecorationStyle(t) => todo!(),
        PropertyDeclaration::TextJustify(text_justify) => todo!(),
        PropertyDeclaration::TextRendering(t) => todo!(),
        PropertyDeclaration::TextTransform(text_transform) => todo!(),
        PropertyDeclaration::TextWrapMode(t) => todo!(),
        PropertyDeclaration::TransformStyle(transform_style) => todo!(),
        PropertyDeclaration::UnicodeBidi(t) => todo!(),
        PropertyDeclaration::Visibility(t) => todo!(),
        PropertyDeclaration::WebkitTextSecurity(t) => todo!(),
        PropertyDeclaration::WhiteSpaceCollapse(t) => todo!(),
        PropertyDeclaration::WordBreak(word_break) => todo!(),
        PropertyDeclaration::WritingMode(writing_mode_property) => todo!(),
        PropertyDeclaration::ZIndex(generic_zindex) => todo!(),
        PropertyDeclaration::Zoom(zoom) => todo!(),
        PropertyDeclaration::AlignContent(content_distribution) => todo!(),
        PropertyDeclaration::JustifyContent(content_distribution) => todo!(),
        PropertyDeclaration::FlexGrow(non_negative) => todo!(),
        PropertyDeclaration::FlexShrink(non_negative) => todo!(),
        PropertyDeclaration::AlignSelf(self_alignment) => todo!(),
        PropertyDeclaration::JustifySelf(self_alignment) => todo!(),
        PropertyDeclaration::OverflowBlock(overflow) => todo!(),
        PropertyDeclaration::OverflowInline(overflow) => todo!(),
        PropertyDeclaration::OverflowX(overflow) => todo!(),
        PropertyDeclaration::OverflowY(overflow) => todo!(),
        PropertyDeclaration::BorderBlockEndStyle(border_style) => todo!(),
        PropertyDeclaration::BorderBlockStartStyle(border_style) => todo!(),
        PropertyDeclaration::BorderBottomStyle(border_style) => todo!(),
        PropertyDeclaration::BorderInlineEndStyle(border_style) => todo!(),
        PropertyDeclaration::BorderInlineStartStyle(border_style) => todo!(),
        PropertyDeclaration::BorderLeftStyle(border_style) => todo!(),
        PropertyDeclaration::BorderRightStyle(border_style) => todo!(),
        PropertyDeclaration::BorderTopStyle(border_style) => todo!(),
        PropertyDeclaration::AnimationComposition(specified_value) => todo!(),
        PropertyDeclaration::AnimationDelay(specified_value) => todo!(),
        PropertyDeclaration::AnimationDirection(specified_value) => todo!(),
        PropertyDeclaration::AnimationDuration(specified_value) => todo!(),
        PropertyDeclaration::AnimationFillMode(specified_value) => todo!(),
        PropertyDeclaration::AnimationIterationCount(specified_value) => todo!(),
        PropertyDeclaration::AnimationName(specified_value) => todo!(),
        PropertyDeclaration::AnimationPlayState(specified_value) => todo!(),
        PropertyDeclaration::AnimationTimeline(specified_value) => todo!(),
        PropertyDeclaration::AnimationTimingFunction(specified_value) => todo!(),
        PropertyDeclaration::BackdropFilter(specified_value) => todo!(),
        PropertyDeclaration::BackgroundAttachment(specified_value) => todo!(),
        PropertyDeclaration::BackgroundClip(specified_value) => todo!(),
        PropertyDeclaration::BackgroundImage(specified_value) => todo!(),
        PropertyDeclaration::BackgroundOrigin(specified_value) => todo!(),
        PropertyDeclaration::BackgroundPositionX(specified_value) => todo!(),
        PropertyDeclaration::BackgroundPositionY(specified_value) => todo!(),
        PropertyDeclaration::BackgroundRepeat(specified_value) => todo!(),
        PropertyDeclaration::BackgroundSize(specified_value) => todo!(),
        PropertyDeclaration::BaselineShift(generic_baseline_shift) => todo!(),
        PropertyDeclaration::BorderImageOutset(rect) => todo!(),
        PropertyDeclaration::BorderImageSlice(generic_border_image_slice) => todo!(),
        PropertyDeclaration::BorderImageWidth(rect) => todo!(),
        PropertyDeclaration::BorderSpacing(generic_border_spacing) => todo!(),
        PropertyDeclaration::BoxShadow(specified_value) => todo!(),
        PropertyDeclaration::CaretColor(generic_caret_color) => todo!(),
        PropertyDeclaration::Clip(generic_clip_rect_or_auto) => todo!(),
        PropertyDeclaration::ClipPath(generic_clip_path) => todo!(),
        PropertyDeclaration::Color(color_property_value) => todo!(),
        PropertyDeclaration::ColorScheme(color_scheme) => todo!(),
        PropertyDeclaration::ColumnWidth(generic_length_percentage_or_auto) => todo!(),
        PropertyDeclaration::ContainerName(container_name) => todo!(),
        PropertyDeclaration::Content(generic_content) => todo!(),
        PropertyDeclaration::CounterIncrement(generic_counter_increment) => todo!(),
        PropertyDeclaration::CounterReset(generic_counter_reset) => todo!(),
        PropertyDeclaration::Cursor(generic_cursor) => todo!(),
        PropertyDeclaration::Filter(specified_value) => todo!(),
        PropertyDeclaration::FlexBasis(generic_flex_basis) => todo!(),
        PropertyDeclaration::FontFamily(font_family) => todo!(),
        PropertyDeclaration::FontSize(font_size) => todo!(),
        PropertyDeclaration::FontVariationSettings(font_settings) => todo!(),
        PropertyDeclaration::GridTemplateAreas(grid_template_areas) => todo!(),
        PropertyDeclaration::LetterSpacing(letter_spacing) => todo!(),
        PropertyDeclaration::LineHeight(generic_line_height) => todo!(),
        PropertyDeclaration::ListStyleType(list_style_type) => todo!(),
        PropertyDeclaration::MaskImage(specified_value) => todo!(),
        PropertyDeclaration::OffsetPath(generic_offset_path) => todo!(),
        PropertyDeclaration::OutlineOffset(border_side_offset) => todo!(),
        PropertyDeclaration::OverflowClipMargin(generic_overflow_clip_margin) => todo!(),
        PropertyDeclaration::Perspective(generic_perspective) => todo!(),
        PropertyDeclaration::PositionTryFallbacks(position_try_fallbacks) => todo!(),
        PropertyDeclaration::Quotes(quotes) => todo!(),
        PropertyDeclaration::Rotate(generic_rotate) => todo!(),
        PropertyDeclaration::Scale(generic_scale) => todo!(),
        PropertyDeclaration::TextIndent(generic_text_indent) => todo!(),
        PropertyDeclaration::TextOverflow(text_overflow) => todo!(),
        PropertyDeclaration::TextShadow(specified_value) => todo!(),
        PropertyDeclaration::Transform(generic_transform) => todo!(),
        PropertyDeclaration::TransformOrigin(generic_transform_origin) => todo!(),
        PropertyDeclaration::TransitionBehavior(specified_value) => todo!(),
        PropertyDeclaration::TransitionDelay(specified_value) => todo!(),
        PropertyDeclaration::TransitionDuration(specified_value) => todo!(),
        PropertyDeclaration::TransitionProperty(specified_value) => todo!(),
        PropertyDeclaration::TransitionTimingFunction(specified_value) => todo!(),
        PropertyDeclaration::Translate(generic_translate) => todo!(),
        PropertyDeclaration::ViewTransitionClass(view_transition_class) => todo!(),
        PropertyDeclaration::ViewTransitionName(view_transition_name) => todo!(),
        PropertyDeclaration::WillChange(will_change) => todo!(),
        PropertyDeclaration::WordSpacing(word_spacing) => todo!(),
        PropertyDeclaration::XLang(xlang) => todo!(),
        PropertyDeclaration::ObjectPosition(generic_position) => todo!(),
        PropertyDeclaration::PerspectiveOrigin(generic_position) => todo!(),
        PropertyDeclaration::GridTemplateColumns(generic_grid_template_component) => todo!(),
        PropertyDeclaration::GridTemplateRows(generic_grid_template_component) => todo!(),
        PropertyDeclaration::BorderImageSource(generic_image) => todo!(),
        PropertyDeclaration::ListStyleImage(generic_image) => todo!(),
        PropertyDeclaration::GridAutoColumns(generic_implicit_grid_tracks) => todo!(),
        PropertyDeclaration::GridAutoRows(generic_implicit_grid_tracks) => todo!(),
        PropertyDeclaration::ColumnGap(generic_length_percentage_or_normal) => todo!(),
        PropertyDeclaration::RowGap(generic_length_percentage_or_normal) => todo!(),
        PropertyDeclaration::GridColumnEnd(generic_grid_line) => todo!(),
        PropertyDeclaration::GridColumnStart(generic_grid_line) => todo!(),
        PropertyDeclaration::GridRowEnd(generic_grid_line) => todo!(),
        PropertyDeclaration::GridRowStart(generic_grid_line) => todo!(),
        PropertyDeclaration::MaxBlockSize(generic_max_size) => todo!(),
        PropertyDeclaration::MaxHeight(generic_max_size) => todo!(),
        PropertyDeclaration::MaxInlineSize(generic_max_size) => todo!(),
        PropertyDeclaration::MaxWidth(generic_max_size) => todo!(),
        PropertyDeclaration::BorderBottomLeftRadius(generic_border_corner_radius) => todo!(),
        PropertyDeclaration::BorderBottomRightRadius(generic_border_corner_radius) => todo!(),
        PropertyDeclaration::BorderEndEndRadius(generic_border_corner_radius) => todo!(),
        PropertyDeclaration::BorderEndStartRadius(generic_border_corner_radius) => todo!(),
        PropertyDeclaration::BorderStartEndRadius(generic_border_corner_radius) => todo!(),
        PropertyDeclaration::BorderStartStartRadius(generic_border_corner_radius) => todo!(),
        PropertyDeclaration::BorderTopLeftRadius(generic_border_corner_radius) => todo!(),
        PropertyDeclaration::BorderTopRightRadius(generic_border_corner_radius) => todo!(),
        PropertyDeclaration::Bottom(generic_inset) => todo!(),
        PropertyDeclaration::InsetBlockEnd(generic_inset) => todo!(),
        PropertyDeclaration::InsetBlockStart(generic_inset) => todo!(),
        PropertyDeclaration::InsetInlineEnd(generic_inset) => todo!(),
        PropertyDeclaration::InsetInlineStart(generic_inset) => todo!(),
        PropertyDeclaration::Left(generic_inset) => todo!(),
        PropertyDeclaration::Right(generic_inset) => todo!(),
        PropertyDeclaration::Top(generic_inset) => todo!(),
        PropertyDeclaration::MarginBlockEnd(generic_margin) => todo!(),
        PropertyDeclaration::MarginBlockStart(generic_margin) => todo!(),
        PropertyDeclaration::MarginBottom(generic_margin) => todo!(),
        PropertyDeclaration::MarginInlineEnd(generic_margin) => todo!(),
        PropertyDeclaration::MarginInlineStart(generic_margin) => todo!(),
        PropertyDeclaration::MarginLeft(generic_margin) => todo!(),
        PropertyDeclaration::MarginRight(generic_margin) => todo!(),
        PropertyDeclaration::MarginTop(generic_margin) => todo!(),
        PropertyDeclaration::PaddingBlockEnd(non_negative) => todo!(),
        PropertyDeclaration::PaddingBlockStart(non_negative) => todo!(),
        PropertyDeclaration::PaddingBottom(non_negative) => todo!(),
        PropertyDeclaration::PaddingInlineEnd(non_negative) => todo!(),
        PropertyDeclaration::PaddingInlineStart(non_negative) => todo!(),
        PropertyDeclaration::PaddingLeft(non_negative) => todo!(),
        PropertyDeclaration::PaddingRight(non_negative) => todo!(),
        PropertyDeclaration::PaddingTop(non_negative) => todo!(),
        PropertyDeclaration::BlockSize(generic_size) => todo!(),
        PropertyDeclaration::Height(generic_size) => todo!(),
        PropertyDeclaration::InlineSize(generic_size) => todo!(),
        PropertyDeclaration::MinBlockSize(generic_size) => todo!(),
        PropertyDeclaration::MinHeight(generic_size) => todo!(),
        PropertyDeclaration::MinInlineSize(generic_size) => todo!(),
        PropertyDeclaration::MinWidth(generic_size) => todo!(),
        PropertyDeclaration::Width(generic_size) => todo!(),
        PropertyDeclaration::BorderBlockEndWidth(border_side_width) => todo!(),
        PropertyDeclaration::BorderBlockStartWidth(border_side_width) => todo!(),
        PropertyDeclaration::BorderBottomWidth(border_side_width) => todo!(),
        PropertyDeclaration::BorderInlineEndWidth(border_side_width) => todo!(),
        PropertyDeclaration::BorderInlineStartWidth(border_side_width) => todo!(),
        PropertyDeclaration::BorderLeftWidth(border_side_width) => todo!(),
        PropertyDeclaration::BorderRightWidth(border_side_width) => todo!(),
        PropertyDeclaration::BorderTopWidth(border_side_width) => todo!(),
        PropertyDeclaration::OutlineWidth(border_side_width) => todo!(),
        PropertyDeclaration::BackgroundColor(color) => todo!(),
        PropertyDeclaration::BorderBlockEndColor(color) => todo!(),
        PropertyDeclaration::BorderBlockStartColor(color) => todo!(),
        PropertyDeclaration::BorderBottomColor(color) => todo!(),
        PropertyDeclaration::BorderInlineEndColor(color) => todo!(),
        PropertyDeclaration::BorderInlineStartColor(color) => todo!(),
        PropertyDeclaration::BorderLeftColor(color) => todo!(),
        PropertyDeclaration::BorderRightColor(color) => todo!(),
        PropertyDeclaration::BorderTopColor(color) => todo!(),
        PropertyDeclaration::OutlineColor(color) => todo!(),
        PropertyDeclaration::TextDecorationColor(color) => todo!(),
        PropertyDeclaration::CSSWideKeyword(wide_keyword_declaration) => todo!(),
        PropertyDeclaration::WithVariables(variable_declaration) => todo!(),
        PropertyDeclaration::Custom(custom_declaration) => todo!(),
    }
  }
}
